name: Packages Prerelease

on:
  pull_request:
    branches:
      - main

jobs:
  packages-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint commit messages
        run: pnpm run lint:commits

      - name: Run CI script
        run: pnpm run ci
